name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-backend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            target/server.jar
            Dockerfile

  deploy:
    needs: build-backend

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: .
      - name: deploy to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./server.jar,Dockerfile"
          target: "/server"
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /server
            docker build -t mein-kochbuch-server .
            docker stop mein-kochbuch-server
            docker rm mein-kochbuch-server
            docker run --name mein-kochbuch-server --env-file ./env -d -p 8080:8080 mein-kochbuch-server

